-- R2-S1-DB-01: Configurable compliance foundation
-- Safe for an existing PostgreSQL database with sample data.
-- Run manually with psql:
--   \i db/migrations/2026-05-31-r2-foundation-shift-photo-source.sql

create extension if not exists pgcrypto;

alter table if exists shifts
    add column if not exists shift_order integer;

update shifts
set shift_order = case code
    when 'SHIFT_1' then 1
    when 'SHIFT_2' then 2
    when 'SHIFT_3' then 3
    when 'SHIFT_4' then 4
    else coalesce(shift_order, 999)
end
where shift_order is null
   or code in ('SHIFT_1', 'SHIFT_2', 'SHIFT_3', 'SHIFT_4');

alter table if exists shifts
    alter column shift_order set default 0;

update shifts
set shift_order = 0
where shift_order is null;

alter table if exists shifts
    alter column shift_order set not null;

create index if not exists idx_shifts_shift_order
    on shifts (shift_order);

alter table if exists attendance_images
    add column if not exists source_reference varchar(500);

alter table if exists report_entries
    add column if not exists source_references text;

do $$
declare
    photo_requirement_id_type text;
    photo_requirement_pk_name text;
    photo_requirement_max_id bigint;
begin
    if to_regclass('public.photo_requirements') is not null then
        select data_type
        into photo_requirement_id_type
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'photo_requirements'
          and column_name = 'id';

        if photo_requirement_id_type = 'uuid' then
            select conname
            into photo_requirement_pk_name
            from pg_constraint
            where conrelid = 'public.photo_requirements'::regclass
              and contype = 'p';

            if photo_requirement_pk_name is not null then
                execute format(
                    'alter table public.photo_requirements drop constraint %I',
                    photo_requirement_pk_name
                );
            end if;

            alter table public.photo_requirements
                add column if not exists id_bigint bigint;

            create sequence if not exists public.photo_requirements_id_seq;

            update public.photo_requirements
            set id_bigint = nextval('public.photo_requirements_id_seq')
            where id_bigint is null;

            select coalesce(max(id_bigint), 0)
            into photo_requirement_max_id
            from public.photo_requirements;

            if photo_requirement_max_id = 0 then
                perform setval('public.photo_requirements_id_seq', 1, false);
            else
                perform setval('public.photo_requirements_id_seq', photo_requirement_max_id, true);
            end if;

            alter table public.photo_requirements
                alter column id_bigint set default nextval('public.photo_requirements_id_seq'),
                alter column id_bigint set not null;

            alter sequence public.photo_requirements_id_seq
                owned by public.photo_requirements.id_bigint;

            alter table public.photo_requirements
                drop column id;

            alter table public.photo_requirements
                rename column id_bigint to id;

            alter sequence public.photo_requirements_id_seq
                owned by public.photo_requirements.id;

            alter table public.photo_requirements
                add constraint photo_requirements_pkey primary key (id);
        end if;
    end if;
end $$;

create table if not exists photo_requirements (
    id bigint generated by default as identity primary key,
    role varchar(30) not null,
    shift_id uuid references shifts(id) on delete cascade,
    image_type varchar(30) not null,
    phase varchar(30) not null,
    required_count integer not null default 1,
    interval_minutes integer,
    active boolean not null default true,
    note varchar(500),
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    constraint ck_photo_requirements_required_count check (required_count >= 0),
    constraint ck_photo_requirements_interval_minutes check (interval_minutes is null or interval_minutes > 0),
    constraint ck_photo_requirements_role check (role in ('INTERN', 'TEAM_LEADER', 'MANAGER', 'ADMIN')),
    constraint ck_photo_requirements_image_type check (image_type in ('PERSONAL_TIMEMARK', 'GROUP')),
    constraint ck_photo_requirements_phase check (phase in ('CHECKIN', 'DURING_SHIFT', 'CHECKOUT'))
);

create unique index if not exists uk_photo_requirement_scope
    on photo_requirements (
        role,
        coalesce(shift_id, '00000000-0000-0000-0000-000000000000'::uuid),
        image_type,
        phase,
        coalesce(interval_minutes, -1)
    );

create index if not exists idx_photo_requirements_role_active
    on photo_requirements (role, active);

create index if not exists idx_photo_requirements_shift
    on photo_requirements (shift_id);

insert into photo_requirements (role, shift_id, image_type, phase, required_count, interval_minutes, active, note)
values
    ('INTERN', null, 'PERSONAL_TIMEMARK', 'CHECKIN', 1, null, true, 'Anh TimeMark vao ca'),
    ('INTERN', null, 'PERSONAL_TIMEMARK', 'DURING_SHIFT', 1, 30, true, 'Moi 30 phut trong ca'),
    ('INTERN', null, 'PERSONAL_TIMEMARK', 'CHECKOUT', 1, null, true, 'Anh TimeMark tan ca'),
    ('INTERN', null, 'GROUP', 'CHECKIN', 1, null, true, 'Anh nhom vao ca neu co nhom'),
    ('INTERN', null, 'GROUP', 'DURING_SHIFT', 1, 60, true, 'Moi 60 phut trong ca neu co nhom'),
    ('INTERN', null, 'GROUP', 'CHECKOUT', 1, null, true, 'Anh nhom tan ca neu co nhom'),
    ('TEAM_LEADER', null, 'PERSONAL_TIMEMARK', 'CHECKIN', 1, null, true, 'Anh TimeMark vao ca'),
    ('TEAM_LEADER', null, 'PERSONAL_TIMEMARK', 'DURING_SHIFT', 1, 30, true, 'Moi 30 phut trong ca'),
    ('TEAM_LEADER', null, 'PERSONAL_TIMEMARK', 'CHECKOUT', 1, null, true, 'Anh TimeMark tan ca'),
    ('TEAM_LEADER', null, 'GROUP', 'CHECKIN', 1, null, true, 'Anh nhom vao ca neu co nhom'),
    ('TEAM_LEADER', null, 'GROUP', 'DURING_SHIFT', 1, 60, true, 'Moi 60 phut trong ca neu co nhom'),
    ('TEAM_LEADER', null, 'GROUP', 'CHECKOUT', 1, null, true, 'Anh nhom tan ca neu co nhom')
on conflict do nothing;

comment on column shifts.shift_order is 'Thu tu hien thi/xu ly ca, dung thay cho parse code SHIFT_n.';
comment on table photo_requirements is 'Cau hinh yeu cau anh diem danh theo role/ca/loai anh/giai doan.';
comment on column photo_requirements.shift_id is 'Null = default cho moi ca; co gia tri = override cho ca cu the.';
comment on column photo_requirements.interval_minutes is 'Khoang lap anh giua ca; null cho moc checkin/checkout co dinh.';
comment on column attendance_images.source_reference is 'Nguon tham chieu/metadata cua anh, dung cho compliance audit.';
comment on column report_entries.source_references is 'Nguon tham khao co cau truc hoac snapshot link phuc vu compliance audit.';
